apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: frontend
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: frontend
          image: gcr.io/canariokubernetestest/python-guestbook-frontend:latest
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GUESTBOOK_API_ADDR
              value: python-guestbook-backend:8080
