name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build Backend Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-guestbook-backend ./src/backend

      - name: Push Backend Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-guestbook-backend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build Frontend Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-guestbook-frontend ./src/frontend

      - name: Push Frontend Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-guestbook-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install Google Cloud CLI
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: autopilot-cluster-1
          location: us-central1

      - name: Set Kubernetes namespace (optional)
        run: |
          kubectl config set-context --current --namespace=default

      - name: Deploy Backend to GKE
        run: |
          kubectl apply -f ./src/backend/kubernetes-manifests

      - name: Deploy Frontend to GKE
        run: |
          kubectl apply -f ./src/frontend/kubernetes-manifests

      - name: Wait for Backend Deployment
        run: |
          kubectl rollout status deployment/python-guestbook-backend

      - name: Wait for Frontend Deployment
        run: |
          kubectl rollout status deployment/python-guestbook-frontend
