name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build Backend Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-backend ./src/backend

      - name: Push Backend Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-backend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build Frontend Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-frontend ./src/frontend

      - name: Push Frontend Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install Google Cloud CLI and gke-gcloud-auth-plugin
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL
          # Install the gke-gcloud-auth-plugin
          gcloud components install gke-gcloud-auth-plugin

      - name: Add Google Cloud SDK GPG Key
        run: |
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/google.asc

      - name: Add Google Cloud SDK repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1

      - name: Set Kubernetes namespace (optional)
        run: |
          kubectl config set-context --current --namespace=default

      - name: Deploy Backend to GKE
        run: |
          kubectl apply -f ./src/backend/kubernetes-manifests

      - name: Deploy Frontend to GKE
        run: |
          kubectl apply -f ./src/frontend/kubernetes-manifests

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/flask-backend
          kubectl rollout status deployment/flask-frontend
